In [1]:
import pandas as pd

df = pd.read_csv("../data/batch2_contracts_125rows.csv")
df.head()

,contract_id,raw_text,apr,term_months,monthly_payment,penalty_clause,recommended_action,risk_flag
0,1,This contract between Prime Auto and Emily Sto...,10.49,24,959,NaN,Approve,Low
1,2,This contract between ABC Motors and Priya Sha...,3.78,24,804,Early termination fee $300,Approve,Low
2,3,This contract between DriveEasy Finance and Sa...,5.41,24,774,Late fee $50,Reject,High
3,4,This contract between National Motors and Alex...,5.26,48,1028,Late fee $25,Approve,High
4,5,This contract between National Motors and John...,5.97,36,1180,NaN,Approve,Low

In [ ]:
# info() shows data types

# describe() shows numeric summaries

# sample() shows random records

In [5]:
def upload_contract(path):
    return path

In [7]:
def extract_text_simulated(raw_text):
    return raw_text

In [10]:
pip install pdfplumber

Defaulting to user installation because normal site-packages is not writeable
Collecting pdfplumber
  Downloading pdfplumber-0.11.8-py3-none-any.whl.metadata (43 kB)
Collecting pdfminer.six==20251107 (from pdfplumber)
  Downloading pdfminer_six-20251107-py3-none-any.whl.metadata (4.2 kB)
Collecting Pillow>=9.1 (from pdfplumber)
  Downloading pillow-12.0.0-cp313-cp313-win_amd64.whl.metadata (9.0 kB)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-5.1.0-py3-none-win_amd64.whl.metadata (67 kB)
Collecting charset-normalizer>=2.0.0 (from pdfminer.six==20251107->pdfplumber)
  Downloading charset_normalizer-3.4.4-cp313-cp313-win_amd64.whl.metadata (38 kB)
Collecting cryptography>=36.0.0 (from pdfminer.six==20251107->pdfplumber)
  Downloading cryptography-46.0.3-cp311-abi3-win_amd64.whl.metadata (5.7 kB)
Collecting cffi>=2.0.0 (from cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber)
  Downloading cffi-2.0.0-cp313-cp313-win_amd64.whl.metadata (2.6 kB)
Collecting pycparser (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20251107->pdfplumber)
  Downloading pycparser-2.23-py3-none-any.whl.metadata (993 bytes)
Downloading pdfplumber-0.11.8-py3-none-any.whl (60 kB)
Downloading pdfminer_six-20251107-py3-none-any.whl (5.6 MB)
   ---------------------------------------- 0.0/5.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/5.6 MB ? eta -:--:--
   --- ------------------------------------ 0.5/5.6 MB 1.4 MB/s eta 0:00:04
   ------- -------------------------------- 1.0/5.6 MB 1.9 MB/s eta 0:00:03
   ----------- ---------------------------- 1.6/5.6 MB 2.0 MB/s eta 0:00:02
   ------------- -------------------------- 1.8/5.6 MB 2.1 MB/s eta 0:00:02
   ---------------- ----------------------- 2.4/5.6 MB 2.0 MB/s eta 0:00:02
   -------------------- ------------------- 2.9/5.6 MB 2.1 MB/s eta 0:00:02
   ------------------------ --------------- 3.4/5.6 MB 2.1 MB/s eta 0:00:02
   -------------------------- ------------- 3.7/5.6 MB 2.1 MB/s eta 0:00:01
   ----------------------------- ---------- 4.2/5.6 MB 2.1 MB/s eta 0:00:01
   --------------------------------- ------ 4.7/5.6 MB 2.2 MB/s eta 0:00:01
   ------------------------------------- -- 5.2/5.6 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------  5.5/5.6 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 5.6/5.6 MB 2.1 MB/s eta 0:00:00
Downloading pillow-12.0.0-cp313-cp313-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.0 MB ? eta -:--:--
   ---- ----------------------------------- 0.8/7.0 MB 2.2 MB/s eta 0:00:03
   ------- -------------------------------- 1.3/7.0 MB 2.3 MB/s eta 0:00:03
   ---------- ----------------------------- 1.8/7.0 MB 2.4 MB/s eta 0:00:03
   ------------- -------------------------- 2.4/7.0 MB 2.4 MB/s eta 0:00:02
   ---------------- ----------------------- 2.9/7.0 MB 2.5 MB/s eta 0:00:02
   -------------------- ------------------- 3.7/7.0 MB 2.5 MB/s eta 0:00:02
   ---------------------- ----------------- 3.9/7.0 MB 2.5 MB/s eta 0:00:02
   ------------------------- -------------- 4.5/7.0 MB 2.5 MB/s eta 0:00:02
   ---------------------------- ----------- 5.0/7.0 MB 2.4 MB/s eta 0:00:01
   ------------------------------- -------- 5.5/7.0 MB 2.4 MB/s eta 0:00:01
   -------------------------------- ------- 5.8/7.0 MB 2.3 MB/s eta 0:00:01
   ----------------------------------- ---- 6.3/7.0 MB 2.3 MB/s eta 0:00:01
   -------------------------------------- - 6.8/7.0 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 2.2 MB/s eta 0:00:00
Downloading pypdfium2-5.1.0-py3-none-win_amd64.whl (3.1 MB)
   ---------------------------------------- 0.0/3.1 MB ? eta -:--:--
   ------ --------------------------------- 0.5/3.1 MB 2.4 MB/s eta 0:00:02
   ---------- ----------------------------- 0.8/3.1 MB 2.1 MB/s eta 0:00:02
   ---------------- ----------------------- 1.3/3.1 MB 2.3 MB/s eta 0:00:01
   ----------------------- ---------------- 1.8/3.1 MB 2.3 MB/s eta 0:00:01
   ------------------------------ --------- 2.4/3.1 MB 2.3 MB/s eta 0:00:01
   ------------------------------------- -- 2.9/3.1 MB 2.3 MB/s eta 0:00:01
   ---------------------------------------- 3.1/3.1 MB 2.1 MB/s eta 0:00:00
Downloading charset_normalizer-3.4.4-cp313-cp313-win_amd64.whl (107 kB)
Downloading cryptography-46.0.3-cp311-abi3-win_amd64.whl (3.5 MB)
   ---------------------------------------- 0.0/3.5 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/3.5 MB 2.5 MB/s eta 0:00:02
   ----------- ---------------------------- 1.0/3.5 MB 2.6 MB/s eta 0:00:01
   ----------------- ---------------------- 1.6/3.5 MB 2.5 MB/s eta 0:00:01
   -------------------- ------------------- 1.8/3.5 MB 2.5 MB/s eta 0:00:01
   -------------------------- ------------- 2.4/3.5 MB 2.4 MB/s eta 0:00:01
   -------------------------------- ------- 2.9/3.5 MB 2.4 MB/s eta 0:00:01
   -------------------------------------- - 3.4/3.5 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 3.5/3.5 MB 2.2 MB/s eta 0:00:00
Downloading cffi-2.0.0-cp313-cp313-win_amd64.whl (183 kB)
Downloading pycparser-2.23-py3-none-any.whl (118 kB)
Installing collected packages: pypdfium2, pycparser, Pillow, charset-normalizer, cffi, cryptography, pdfminer.six, pdfplumber
Successfully installed Pillow-12.0.0 cffi-2.0.0 charset-normalizer-3.4.4 cryptography-46.0.3 pdfminer.six-20251107 pdfplumber-0.11.8 pycparser-2.23 pypdfium2-5.1.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
import pdfplumber

def extract_text_pdf(path):
    text = ""
    with pdfplumber.open("../data/"+ path) as pdf:
        for page in pdf.pages:
            text += page.extract_text() + "\n"
    return text

In [12]:
processed = []

for i, row in df.iterrows():
    text = extract_text_simulated(row['raw_text'])
    
    processed.append({
        "contract_id": row['contract_id'],
        "extracted_text": text
    })

df_extracted = pd.DataFrame(processed)
df_extracted.head()

   contract_id                                     extracted_text
0            1  This contract between Prime Auto and Emily Sto...
1            2  This contract between ABC Motors and Priya Sha...
2            3  This contract between DriveEasy Finance and Sa...
3            4  This contract between National Motors and Alex...
4            5  This contract between National Motors and John...

In [13]:
import re

def parse_fields(text):
    result = {}

    # APR
    apr = re.search(r'APR[: ]+(\d+\.?\d*)%', text)
    result['apr'] = float(apr.group(1)) if apr else None

    # Term
    term = re.search(r'(\d+)\s+months', text)
    result['term_months'] = int(term.group(1)) if term else None

    # Payment
    pay = re.search(r'payment[: ]+\$?(\d+)', text)
    result['monthly_payment'] = int(pay.group(1)) if pay else None

    # Penalty
    penalty = re.search(r'(late fee \$\d+|early termination fee \$\d+|none)', text.lower())
    result['penalty'] = penalty.group(1) if penalty else None

    return result

parsed = df_extracted['extracted_text'].apply(parse_fields)
parsed_df = pd.DataFrame(parsed.tolist())
parsed_df.head()

     apr  term_months  monthly_payment                     penalty
0  10.49           24              959                        none
1   3.78           24              804  early termination fee $300
2   5.41           24              774                late fee $50
3   5.26           48             1028                late fee $25
4   5.97           36             1180                        none

In [15]:
output = pd.concat([df_extracted, parsed_df], axis=1)
output.to_csv("../data/milestone1_output_suresh.csv", index=False)

In [2]:
df.info()
df.describe()
df.sample(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   contract_id         125 non-null    int64
 1   raw_text            125 non-null    object
 2   apr                 125 non-null    float64
 3   term_months         125 non-null    int64
 4   monthly_payment     125 non-null    int64
 5   penalty_clause      93 non-null     object
 6   recommended_action  125 non-null    object
 7   risk_flag           125 non-null    object
dtypes: float64(1), int64(3), object(4)
memory usage: 7.9+ KB

,contract_id,raw_text,apr,term_months,monthly_payment,penalty_clause,recommended_action,risk_flag
95,96,This contract between National Motors and Rahu...,2.63,36,287,Late fee $50,Reject,Medium
11,12,This contract between DriveEasy Finance and Em...,12.77,48,610,NaN,Approve,Low
92,93,This contract between DriveEasy Finance and Ra...,13.15,24,485,Early termination fee $300,Approve,Medium
110,111,This contract between ABC Motors and Emily Sto...,2.91,48,923,NaN,Reject,Medium
85,86,This contract between ABC Motors and Rahul Ver...,5.70,48,371,Late fee $25,Approve,Medium

In [ ]:
# We will now build a simple parser that extracts 
# APR, term, payments, penalties using Python rules.
# This gives:

# APR

# Term

# Monthly payment

# Penalty

In [3]:
def parse_contract(text):
    result = {}

    # Extract APR
    import re
    apr_match = re.search(r'APR (\d+\.?\d*)%', text)
    result['apr_extracted'] = float(apr_match.group(1)) if apr_match else None

    # Extract term
    term_match = re.search(r'(\d+) months', text)
    result['term_extracted'] = int(term_match.group(1)) if term_match else None

    # Extract payment
    payment_match = re.search(r'monthly payment \$?(\d+)', text)
    result['monthly_payment_extracted'] = int(payment_match.group(1)) if payment_match else None

    # Extract penalty
    penalty_match = re.search(r'(Late fee \$\d+|Early termination fee \$\d+|None)', text)
    result['penalty_extracted'] = penalty_match.group(1) if penalty_match else None

    return result

parsed = df['raw_text'].apply(parse_contract)
parsed_df = pd.DataFrame(parsed.tolist())
parsed_df.head()

,apr_extracted,term_extracted,monthly_payment_extracted,penalty_extracted
0,10.49,24,959,None
1,3.78,24,804,Early termination fee $300
2,5.41,24,774,Late fee $50
3,5.26,48,1028,Late fee $25
4,5.97,36,1180,None

In [ ]:
# Now we create simple rule-based risk detection.
# This is NOT ML — just Python logic

In [4]:
def risk_rule(row):
    if row['apr'] > 10:
        return "HIGH"
    if row['monthly_payment'] > 900:
        return "MEDIUM"
    return "LOW"

df['rule_based_risk'] = df.apply(risk_rule, axis=1)
df[['raw_text', 'rule_based_risk']].head()

                                            raw_text rule_based_risk
0  This contract between Prime Auto and Emily Sto...            HIGH
1  This contract between ABC Motors and Priya Sha...             LOW
2  This contract between DriveEasy Finance and Sa...             LOW
3  This contract between National Motors and Alex...          MEDIUM
4  This contract between National Motors and John...          MEDIUM